### ISSUE TITLE
KeyError: 'lagrangian_dataset' 

### ISSUE THREAD

**Issue by Huzaifg** [ml-jku/UPT#2]
Hello,
First, thanks for open sourcing your code and that too in such an extensive way. This really helps!

I am trying to reproduce the Lagrangian 3D results from your paper. From what I understand, the Lagrangian dataset does not require anything from the user's side to download. However, when I run

`python main_train.py --devices 0 --hp <PATH-TO-UPT-REPO>/src/yamls/lagrangian/tgv3d.yaml`

I get this error 

```bash
Traceback (most recent call last):
  File "/srv/home/unjhawala/UPT/src/main_train.py", line 96, in <module>
    main()
  File "/srv/home/unjhawala/UPT/src/main_train.py", line 86, in main
    run_single_or_multiprocess(
  File "/srv/home/unjhawala/UPT/src/distributed/run.py", line 89, in run_single_or_multiprocess
    main_single(device=device)
  File "/srv/home/unjhawala/UPT/src/main_train.py", line 64, in main_single
    train_stage(
  File "/srv/home/unjhawala/UPT/src/train_stage.py", line 180, in train_stage
    datasets[dataset_key] = dataset_from_kwargs(
  File "/srv/home/unjhawala/UPT/src/datasets/__init__.py", line 13, in dataset_from_kwargs
    dataset = instantiate(
  File "/srv/home/unjhawala/UPT/src/utils/factory.py", line 73, in instantiate
    return obj_type(**kwargs, **ctor_kwargs, **optional_kwargs)
  File "/srv/home/unjhawala/UPT/src/datasets/lagrangian_dataset.py", line 65, in __init__
    global_root, local_root = self._get_roots(global_root, local_root, "lagrangian_dataset")
  File "/srv/home/unjhawala/UPT/src/datasets/base/dataset_base.py", line 25, in _get_roots
    global_root = self._get_global_root(global_root, dataset_identifier)
  File "/srv/home/unjhawala/UPT/src/datasets/base/dataset_base.py", line 38, in _get_global_root
    global_root = self.dataset_config_provider.get_global_dataset_path(dataset_identifier)
  File "/srv/home/unjhawala/UPT/src/providers/dataset_config_provider.py", line 17, in get_global_dataset_path
    path = self.global_dataset_paths[dataset_identifier]
KeyError: 'lagrangian_dataset'
```

The entire log is attached (removed some wandb private info)
[dump.txt](https://github.com/ml-jku/UPT/files/14499964/dump.txt)

**Comment by OmerRochman** [comment]
+1 this should be added to `SETUP_DATA.md` 👍 , it is a bit hidden here

**Comment by BenediktAlkin** [comment]
Fixed the static_config_template.yaml and updated the SETUP_DATA.md to include instructions to create the director. Thanks!
